# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f194ed52f28adec3146967e209153fe3f3cd4c2c3f5d65f1bc8bbcd19d189ad15d7bcf585fdf0f634e9d747fe306836d6719a1426db52115ec1a1f3a9f88b20

test:
  secret_key_base: 606315241f70c4c35c3a994a7cc895ff4da411e251f4c3b6022c328e68672c39a772bafcf77e62b19d0938b10c40518993ed3f6cded7e55d35bfaf98c6224484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
